---
- name: Check if nginx is already installed.
  stat: path=/etc/init.d/nginx
  register: nginx_installed

- name: Add the Nginx source to the APT source list
  apt_repository: repo="ppa:nginx/stable" state=present
  when: nginx_installed.stat.exists == false
  tags:
    - nginx-installation

- name: Install Nginx
  apt: name={{item}} state=installed
  with_items:
   - nginx
   - nginx-extras
   - openssl
  tags:
    - nginx-installation

- name: Stop Nginx
  service: name=nginx state=stopped
  when: nginx_installed.stat.exists == false
  tags:
    - nginx-configuration

- name: Configure Nginx
  template: src=nginx.j2 dest=/etc/nginx/nginx.conf
  when: nginx_installed.stat.exists == false
  tags:
    - nginx-configuration

- name: Start Nginx
  service: name=nginx state=started
  tags:
    - nginx-configuration
