---
#databases
- name: Ensure MySQL databases are present.
  mysql_db:
    name: account
    collation: utf8_general_ci
    encoding: utf8
    state: present

- name: Ensure MySQL users are present.
  mysql_user:
    name: obsession
    host: localhost
    password: password
    priv: 'account.*:ALL'
    state: present
    append_privs: no
    encrypted: no
  no_log: true
- name: Installing db migrations
  shell: /var/www/obsession/yii migrate/up --interactive=0
